"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path
from urllib.parse import urlparse

from dotenv import load_dotenv
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY')
if not SECRET_KEY:
    raise ImproperlyConfigured('SECRET_KEY is required. Set it in backend/.env')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = False

ALLOWED_HOSTS = [h.strip() for h in os.environ.get('ALLOWED_HOSTS', '*').split(',') if h.strip()] or ['*']
CSRF_TRUSTED_ORIGINS = [
    o.strip()
    for o in os.environ.get('CSRF_TRUSTED_ORIGINS', 'https://*.up.railway.app').split(',')
    if o.strip()
]

# Trailing slashes in urlpatterns; CommonMiddleware also appends slash on 404.
APPEND_SLASH = True

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_q',
    'subscriptions.apps.SubscriptionsConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'core.middleware.EnsureApiTrailingSlashMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

def _database_from_url(url: str) -> dict:
    u = urlparse(url)
    if u.scheme in ('postgres', 'postgresql'):
        return {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': (u.path or '').lstrip('/') or 'postgres',
            'USER': u.username or 'postgres',
            'PASSWORD': u.password or '',
            'HOST': u.hostname or 'localhost',
            'PORT': str(u.port or 5432),
        }
    if u.scheme == 'sqlite':
        name = (u.path or '').lstrip('/') or str(BASE_DIR / 'db.sqlite3')
        return {'ENGINE': 'django.db.backends.sqlite3', 'NAME': name}
    raise ImproperlyConfigured(f'Unsupported DATABASE_URL scheme: {u.scheme}')


DATABASE_URL = os.environ.get('DATABASE_URL', '').strip()
if DATABASE_URL:
    DATABASES = {'default': _database_from_url(DATABASE_URL)}
elif os.environ.get('POSTGRES_DB'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.environ['POSTGRES_DB'],
            'USER': os.environ.get('POSTGRES_USER', 'postgres'),
            'PASSWORD': os.environ.get('POSTGRES_PASSWORD', ''),
            'HOST': os.environ.get('POSTGRES_HOST', 'localhost'),
            'PORT': os.environ.get('POSTGRES_PORT', '5432'),
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }

CORS_ALLOWED_ORIGINS = [
    'http://localhost:5173',
    'http://127.0.0.1:5173',
]
# Production: comma-separated extra origins (e.g. https://your-app.onrender.com)
_extra_cors = os.environ.get('CORS_ALLOWED_ORIGINS', '').strip()
if _extra_cors:
    CORS_ALLOWED_ORIGINS = CORS_ALLOWED_ORIGINS + [
        o.strip() for o in _extra_cors.split(',') if o.strip()
    ]


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Django REST framework — global auth; per-view AllowAny for login/register/refresh
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=15),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
}

# Stock quotes: Redis (cross-process); Railway injects REDIS_URL.
REDIS_URL = os.environ.get('REDIS_URL', 'redis://127.0.0.1:6379/0')
REDIS_CACHE_URL = os.environ.get('REDIS_CACHE_URL', REDIS_URL)
CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_CACHE_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        },
        'KEY_PREFIX': 'stock',
        'TIMEOUT': None,
    }
}

# Django Q2 — broker via Redis URL (defaults to REDIS_URL).
def _parse_redis_url(url: str) -> dict:
    u = urlparse(url)
    path = (u.path or '').lstrip('/')
    db = int(path) if path.isdigit() else int(os.environ.get('REDIS_Q_DB', '2'))
    return {
        'host': u.hostname or '127.0.0.1',
        'port': u.port or 6379,
        'db': db,
        'password': u.password or os.environ.get('REDIS_Q_PASSWORD') or None,
    }


REDIS_Q_URL = os.environ.get('REDIS_Q_URL', REDIS_URL)
_q_redis = _parse_redis_url(REDIS_Q_URL)
if os.environ.get('REDIS_Q_HOST'):
    _q_redis['host'] = os.environ['REDIS_Q_HOST']
if os.environ.get('REDIS_Q_PORT'):
    _q_redis['port'] = int(os.environ['REDIS_Q_PORT'])
if os.environ.get('REDIS_Q_DB'):
    _q_redis['db'] = int(os.environ['REDIS_Q_DB'])

Q_CLUSTER = {
    'name': 'stock_subscription',
    'workers': 4,
    'timeout': 120,
    'retry': 180,
    'queue_limit': 100,
    'bulk': 10,
    'redis': _q_redis,
}

# True → get_price() uses random prices; validate_ticker still prefers real yfinance checks.
YFINANCE_MOCK = os.environ.get('YFINANCE_MOCK', '0').lower() in (
    '1',
    'true',
    'yes',
)
PRICE_CACHE_TTL = int(os.environ.get('PRICE_CACHE_TTL', '120'))

# Email: console in dev by default; Gmail SMTP when USE_GMAIL_SMTP=1.
USE_GMAIL_SMTP = os.environ.get('USE_GMAIL_SMTP', '0').lower() in ('1', 'true', 'yes')
if USE_GMAIL_SMTP:
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
    EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
    EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
    EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', '1').lower() in ('1', 'true', 'yes')
    EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
    EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
else:
    EMAIL_BACKEND = os.environ.get(
        'EMAIL_BACKEND', 'django.core.mail.backends.console.EmailBackend'
    )

DEFAULT_FROM_EMAIL = os.environ.get(
    'DEFAULT_FROM_EMAIL', os.environ.get('EMAIL_HOST_USER', 'noreply@stock-subscription.local')
)
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# OpenAI (demo signals — not financial advice)
OPENAI_API_KEY = os.environ.get('OPENAI_API_KEY', '')
OPENAI_MODEL = os.environ.get('OPENAI_MODEL', 'gpt-4o')
