# Generated by Django 6.0.3 on 2026-04-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='ticker',
            field=models.CharField(db_index=True, max_length=20),
        ),
    ]
